# Throw Exceptions
## Pass the Exceptions
* When a method throws an exception, if the current method doesn't catch it, it will be passed to higher level until there's ```try...catch```
    ```java
    public class Main {
        public static void main(String[] args) {
            try {
                process1();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        static void process1() {
            process2();
        }

        static void process2() {
            Integer.parseInt(null); // 会抛出NumberFormatException
        }
    }
    ```
* Use ```printStackTrace()``` to print out the exception information
    ```
    java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at Main.process2(Main.java:16)
        at Main.process1(Main.java:12)
        at Main.main(Main.java:5)
    ```
* Read it from bottom to top
  1. ```main()``` calls ```process1()```
  2. ```process1()``` calls ```process2()```
  3. ```process2()``` calls ```Integer.parseInt(String)```
  4. ```Integer.parseInt(String)``` calls ```Integer.parseInt(String, int)```
---
## Throw Exceptions
* 